[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"

[ja]
  languageName = "Jananese"
  contentDir = "content/ja"
  weight = 15
  [ja.params]
    languageISO = "JA"
    languageTag = "ja-JA"
