name = "Bit Banana"
license = "MIT"
licenselink = "https://github.com/bitbanana/blob/main/LICENSE"
description = "bitbananaの説明をここに書きます"

homepage = "https://github.com/bitbanana"
demosite = "https://github.com/bitbanana"

tags = ["bitbanana", "coin", "game"]
features = ["proof of stake", "blockchain"]

[author]
  name = "rbdog"
  homepage = "https://rbdog.test.test"
